version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ngins:laste .
      - docker tag nginx:laste 391122691900.dkr.ecr.us-east-2.amazonaws.com/nginx:laste
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 391122691900.dkr.ecr.us-east-2.amazonaws.com/nginx:laste