version: '3'
services:
  back-front:
    build:
      context: ./back-front/
      dockerfile: Dockerfile
    image: back-front
    environment:
      HTTP_BASE_API: 47.52.249.35:8080
    ports:
      - "8081:8080"
  back-back:
    build:
      context: ./back-back/
      dockerfile: Dockerfile
    image: back-back
    environment:
      PROJECT_MYSQL_HOSTNAME: 172.17.0.1
      PROJECT_MYSQL_PORT: 3306
      PROJECT_MYSQL_USERNAME: root
      PROJECT_MYSQL_PASSWORD: Jz123456
      PROJECT_REDIS_HOSTNAME: 172.17.0.1
      PROJECT_REDIS_PORT: 6379
      PROJECT_REDIS_PASSWORD:
      ROBOT_URL_8692: 172.17.0.1
      GAME_URL_8691: 172.17.0.1
      AGENT_URL_6002: 172.17.0.1
      PROJECT_LOG_PATH: /home/web/logs/ozygod-pm
      PROJECT_CHECK_WHITELIST: 'false'
      PROJECT_CHECK_GOOGLECODE: 'false'
    volumes:
      - /home/web/logs/ozygod-pm:/home/web/logs/ozygod-pm
      - /home/web/files:/home/web/files
    ports:
      - "8080:8080"
    restart: always
